FROM python:3.9
LABEL maintainer "edberg1974 <edberg.s@gmail.com>"

COPY ./app/service_1.py /app
COPY ./data /data
ENV IMAGEPATH '../data'

WORKDIR /app
RUN pip3 install numpy && pip3 install pillow

ENTRYPOINT [ "python3" ]
CMD ["service_1.py"]