FROM python:3.9-slim
LABEL maintainer "edberg1974 <edberg.s@gmail.com>"

COPY ./app/service2.py /app
COPY ./model /model
ENV MODELPATH '../model'

WORKDIR /app
RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3" ]
CMD ["service_2.py"]