FROM python:3.9
LABEL maintainer "edberg1974 <edberg.s@gmail.com>"

COPY ./app /app
COPY ./model /model
COPY ./data /data
ENV IMAGEPATH '../data'

WORKDIR /app
RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3" ]
CMD ["service_1.py"]